config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users

  get 'pages/about'
  get '/dashboard' => 'users#dashboard'

  resources :users do
    resources :sites, shallow: true
  end

  get 'all_sites' => 'sites#all_sites'

  resources :sites, only: [:show, :edit, :update, :destroy] do
    resources :comments, module: :sites
  end

  resources :comments, only: :destroy

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read_at: nil) }
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :users, through: :comments

  validates :link, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sites, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    dashboard_path
  end

end

app/controllers/comments_controller.rb
require 'notify'

class CommentsController < ApplicationController
  include Notify
  before_action :authenticate_user!

  def create
  @comment = @commentable.comments.new(comment_params)
  @comment.user = current_user
    #   #Module in "lib/notify.rb"
    affirm_notification(@comment)
    if @comment.save
      respond_to do |format|
        # format.html { redirect_to @commentable, :notice => "Comment Created Successfully." }
        format.html { redirect_to dashboard_path, :notice => "Comment Created Successfully." }
        format.js
      end
    else
      redirect_to @commentable, alert: "Something went wrong..."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path, notice: "Comment Deleted Successfully.")
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def create
  end

  def index
    @notifications = Notification.where(recipient: current_user).order('created_at DESC').unread
  end

  def mark_as_read
    @notifications = Notification.where(recipient: current_user).unread
    @notifications.update_all(read_at: Time.zone.now)
    render json: {success: true}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/sites/comments_controller.rb
class Sites::CommentsController < CommentsController
  before_action :authenticate_user!
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Site.find(params[:site_id])
  end

end

app/controllers/sites_controller.rb
require 'scrape'

class SitesController < ApplicationController
  include Scrape
  before_action :set_site, only: %i[ show edit update destroy ]

  def all_sites
    @user = current_user
    @sites = Site.all.order("created_at DESC")
  end

  # GET /sites or /sites.json
  def index
    @user = User.find(params[:user_id])
    @sites = @user.sites.order("created_at DESC")
  end

  # GET /sites/1 or /sites/1.json
  def show
    @site = Site.find(params[:id])
  end

  # GET /sites/new
  def new
    @user = User.find(params[:user_id])
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites or /sites.json
  def create
    @user = current_user
    @site = Site.new(site_params)
    #   #Module in "lib/scrape.rb"
    get_site(params[:site][:link])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1 or /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: "Site was successfully updated." }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1 or /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to user_sites_path(current_user), notice: "Site was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def site_params
      params.require(:site).permit(:link, :title, :thumbnail_link, :description, :keyword_list, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @sites = current_user.sites.order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_or_registration
    true if  (controller_name == "sites") || (controller_name == "registrations")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<div>
  <div style="font-size:150%;">
    <%=  commentable.comments.count %> <%= "#{commentable.comments.size == 1 ? 'Comment' : 'Comments'}"%>
  </div>
  <% commentable.comments.each do |comment| %>
    <div class="text-center p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <br>
      <div style="font-size:150%;">
        <%= comment.body %>
        <div class="text-xs">
          <%= comment.user.email %>
        </div>

      </div>

      <% if current_user %>
      <br>
      <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-danger" if comment.user == current_user %>
      <% end %>
    </div>
    <br>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |form|%>
  <% form.hidden_field :user_id %>
  <%= form.text_area :body, class:"form-control", placeholder:"Add a Comment" %>
  <br>
  <div class="actions btn btn-success">
    <%= button_tag(type: 'submit') do %>
      Submit
    <% end %>
  </div>
  <% end %>

app/views/layouts/_nav.html.erb
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
<nav class="navbar navbar-expand-lg bg-gray-100 navbar-light">
  <% if current_user.present? == false %>
    <a class="navbar-brand" href="/">YouTube Scraper</a>
  <% else %>
    <a class="navbar-brand" href="<%= dashboard_path %>">YouTube Scraper</a>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">

    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Dashboard", dashboard_path, class:"nav-link" if current_user %>
      </li>

      <li class="nav-item">
        <%= link_to "Sites", all_sites_path, class:"nav-link" %>
      </li>

      <%= render "notifications/nav_dropdown" %>


      <!-- <li class="nav-item">
        <%= link_to "About", pages_about_path, class:"nav-link"%>
      </li> -->

    </ul>

    <div class="navbar-text">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class:"nav-link" unless current_user  %>
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class:"nav-link" unless current_user  %>
          <%= link_to "Account Settings", edit_user_registration_path, class:"nav-link" if user_signed_in? %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouTube Scraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'notifications', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-indigo-100">
    <%= render "layouts/nav"%>
    <div class="container text-center pt-10 pb-10 bg-gray-100">
      <!-- <span id="isLoggedIn">
        <%= current_user.email if current_user%>
      </span> -->
      <div class="msg-container text-center">
        <% if notice || alert %>
        <span class="notice text-green-700 text-2xl"><%= notice %></span>
        <span class="alert text-red-700 text-2xl"><%= alert %></span>
        <% end %>
      </div>
      <div class="pl-2 pr-2 h-full">
        <div class="container pb-4">

          <div class="text-center p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
            <div style="width:100%;">
              <div class="display-1" style="font-size:200%;">
                <%= "#{controller_name.capitalize}" %>
                <br>
                <%= "##{action_name.capitalize}" %>
              </div>
            </div>
          </div>
        </div>
        <%= yield %>
        <% if site_or_registration %>
        <div>
          <hr>
          <br>
          <div>
            <%= link_to "Back", :back, class:"btn btn-primary"  %>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script type="text/javascript">

      var customer = $( "#isLoggedIn" ).text().trim()

      setTimeout(function(){
        $('.msg-container').fadeOut().remove();
      }, 3000);

    </script>
  </body>
</html>

app/views/notifications/_index.html.erb
Notifications


<!-- Drop  Down -->
<div class="dropdown-menu" aria-labelledby="navbarDropdown">


<div class="dropdown-item">
<% if @notifications %>
<% @notifications.each_with_index do | notification, index |%>

  <div id="notification-<%= notification.id %>">
    <div class=" text-center">

      <span class="text-gray-600 text-sm">
        <%= index + 1 %>)
      </span>

      <span>
      <%= "#{notification.actor.email } #{notification.action} a #{notification.notifiable.class.to_s.underscore.humanize} on"%>

      <%= link_to "#{notification.notifiable.commentable.title}", site_url(notification.notifiable.commentable) %>
      </span>

      <br>

      <span class="text-gray-600 text-sm">
        <%= "#{time_ago_in_words(notification.created_at)} ago" %>
      </span>

    </div>

  </div>
<% end %>
<hr>
<div class="text-center" id="mark-as-read">
  Mark As Read
</div>
<% else %>
<div class="text-center" id="mark-as-read">
  No New Notifications
</div>
<% end %>

</div>

</div>

app/views/notifications/_nav_dropdown.html.erb
<% if current_user && current_user.notifications.any? %>
<li class="nav-item dropdown invisible" data-behavior="notification-items" id="notifications-nav-dropdown">
  <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="notification-count"></span>
    <%#= render "notifications/index"%>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <div class="notification-count center" style="font-size:150%;"> </div>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item -mt-4" href="" id="notification-resp"></a>
      <div class="dropdown-divider"></div>
      <a href="#" class="center" id="mark-as-read"> Mark as Read</a>
    </div>
  </a>
</li>
<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/sites/_form.html.erb
<%= form_with(model: [ @user, @user.sites.build ]) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>
      <ul>
        <% site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id  %>

  <div class="field">
    <%= form.label :link, "YouTube Video Link:" %>
    <%= form.text_field :link, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :description,"Description(Optional)" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>
  <br>
  <div class="actions btn btn-success">
    <%= button_tag(type: 'submit') do %>
      Create Site
    <% end %>
  </div>

<% end %>

app/views/sites/_index.html.erb
<div class=" container">
  <%= link_to 'Add Site', new_user_site_path(current_user), class:"btn btn-lg btn-success btn-block" if current_user %>
</div>
<% @sites.each do |site| %>
  <% if current_user %>
    <br>
    <div class="float-right pr-4">
      <%= link_to "Posted by: #{site.user.email}", user_sites_path(site.user) unless site.user.email == current_user.email %>
    </div>
  <% else %>
    <div class="float-right pr-4">
      <%= link_to "Posted by: #{site.user.email}", user_sites_path(site.user) %>
    </div>
  <% end %>
  <div class="container p-4 pt-4">
    <div class=" pb-4">
        <div class="text-center p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
          <div class="">
            <img src="<%= site.thumbnail_link %>" alt="site-thumbnail" class="center">
          </div>
          <br>
          <div class="p-2" style="font-size:150%;" >
            <!-- <%= link_to site.title, url_for(site.link), :target => "_blank" %> -->
            <%= link_to site.title, site %>
          </div>
          <div>
            <%= site.description %>
          </div>
          <br>
          <div>
            <strong>Keywords:</strong>
            <%= site.keyword_list %>
          </div>
          <br>
          <div>
            <%= link_to 'View', site, class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/sites/_toggle_button.html.erb
<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-outline-success active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Public
  </label>
  <label class="btn btn-outline-success">
    <input type="radio" name="options" id="option3" autocomplete="off"> Private
  </label>
</div>

app/views/sites/all_sites.html.erb
<%= render "sites/index" %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %>
<td><%= link_to 'Destroy', @site, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/sites/index.html.erb
<%= render "sites/index" %>

app/views/sites/new.html.erb
<div class="container">
  <div class="p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
    <br>
    <div style="font-size:150%;" >
      <%= render 'form', site: @site %>
    </div>
  </div>
</div>

app/views/sites/show.html.erb
<div class="container">
  <div class="pb-4">
    <div class="text-center p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
      <br>
      <div>
        <img src="<%= @site.thumbnail_link %>" alt="" class="center">
      </div>
      <br>
      <div style="font-size:150%;">
         <%= link_to "#{@site.user.email}", user_sites_path(@site.user) %> Posted:
      </div>
      <div style="font-size:150%;">
         <%= @site.title %>
      </div>

      <br>
      <div>
        <strong>YouTube Link:</strong>
        <%= link_to @site.link, url_for(@site.link), :target => "_blank" %>
      </div>
      <br>
      <div>
        <strong>Keywords:</strong>
        <%= @site.keyword_list %>
      </div>
      <br>
      <% if @site.user == current_user %>
        <div>
          <hr>
          <%= link_to 'Delete Video', @site, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        </div>
      <% end %>
      <hr>
      <%= render partial: "comments/comments", locals:{commentable: @site } %>
      <% if current_user %>
      <br>
      <%= render partial: "comments/form", locals:{commentable: @site }%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<% if current_user && current_user.notifications.any? %>
<div class="container">
  <div class="text-center p-4 border-t-2 border-r-2 border-b-2 border-l-4 border-gray-200">
    <div style="font-size:120%;">
      Click button to recieve Push Notifications for <%= current_user.email %>
    </div>
    <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Notifications (Trigger Options)
    </button>
  </div>
</div>
<br>

<% end %>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Notifications</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body p-4">
        <%= link_to 'Alert Group Notifications', root_path, remote: true, id:"group-alerts", class:"btn btn-outline-primary" %>
        <br>
        <br>
        <%= link_to 'Alert Individual Notifications', root_path, remote: true, id:"individual-alerts", class:"btn btn-outline-success" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<%= render "sites/index" %>

<!-- vvvvv ( Included for example use and only on this page) vvvvv -->
<!-- Real notification functionality located in app/javascript/channels/notification_channel.js -->
<script type="text/javascript">

$(document).ready(function(){

  var csrfToken = document.querySelector('[name=csrf-token]')
  var settings = {
    "url": "/notifications.json",
    "method": "GET",
    'x-csrf-token': csrfToken.content,
    "headers": {
      "cache-control": "no-cache",
    }
  }
  $( "#group-alerts" ).click(function() {
    $.ajax(settings).done(function (response) {
      // // One notification to alert amount of Notifications
      var amountOfNotifications = response.length
      var notificationText = (amountOfNotifications <= 0) ? "Notification" : "Notifications";
      var title = "YouTubeScraper"
      var body = amountOfNotifications + " New " + notificationText
      var options = { body: body }
      new Notification(title, options)

    });
  });
  $( "#individual-alerts" ).click(function() {
    $.ajax(settings).done(function (response) {
      // // Multiple individual Notifications
      items = $.map( response, function( val, i ) {
          var title = "YouTubeScraper"
          var body = `${val.message.substring(0,80)}...`
          var options = { body: body }
          new Notification(title, options)
      })
    })
  });

});

</script>